server {
    listen 80;
    server_name proxy.freeuploadmanager.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name proxy.freeuploadmanager.org;

    ssl_certificate /etc/letsencrypt/live/proxy.freeuploadmanager.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/proxy.freeuploadmanager.org/privkey.pem;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_request_buffering off;
        client_max_body_size 0;
    }
}
